# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='股票代码', max_length=20, verbose_name='ticker')),
                ('price_max', models.FloatField(blank=True, help_text='股价上涨到', null=True, verbose_name='price_max')),
                ('price_min', models.FloatField(blank=True, help_text='股价下跌到', null=True, verbose_name='price_min')),
                ('percent_max', models.FloatField(blank=True, help_text='日涨幅超', null=True, verbose_name='percent_max')),
                ('percent_min', models.FloatField(blank=True, help_text='日跌幅超', null=True, verbose_name='percent_min')),
                ('percent_max_10', models.FloatField(blank=True, help_text='涨停', null=True, verbose_name='percent_max_10')),
                ('percent_min_10', models.FloatField(blank=True, help_text='跌停', null=True, verbose_name='percent_min_10')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
