# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='percent_max_10',
            field=models.BooleanField(default=True, help_text='涨停', verbose_name='percent_max_10'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='percent_min_10',
            field=models.BooleanField(default=True, help_text='跌停', verbose_name='percent_min_10'),
        ),
    ]
