# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0002_auto_20190225_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='name',
            field=models.CharField(blank=True, help_text='股票名称', max_length=20, null=True, verbose_name='ticker_name'),
        ),
    ]
