# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0003_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='cost',
            field=models.FloatField(default=0, help_text='成本价', verbose_name='cost'),
        ),
    ]
