# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0004_custom_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='stop_loss',
            field=models.FloatField(default=0, help_text='止损线', verbose_name='percent_min'),
        ),
        migrations.AddField(
            model_name='custom',
            name='target_profit',
            field=models.FloatField(default=0, help_text='止盈线', verbose_name='percent_min'),
        ),
    ]
