# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0005_auto_20190320_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='wechate_account',
            field=models.CharField(default='yejunzhou', help_text='企业微信账户', max_length=20, verbose_name='wechate_account'),
        ),
    ]
